# Generated by Django 4.1.4 on 2022-12-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartaxes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carservice',
            name='car',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='cars.carinfo'),
        ),
        migrations.AlterField(
            model_name='cartaxes',
            name='car',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='cars.carinfo'),
        ),
    ]
